package com.questhelper.helpers.playerguide;

import net.runelite.api.ItemID;
import net.runelite.api.NpcID;
import net.runelite.api.ObjectID;
import net.runelite.api.coords.WorldPoint;
import com.questhelper.BasicQuestHelper;
import com.questhelper.QuestStep;
import com.questhelper.steps.*;
import com.questhelper.requirements.*;
import com.questhelper.requirements.item.ItemRequirement;
import com.questhelper.requirements.item.ItemRequirements;
import com.questhelper.panel.PanelDetails;
import com.questhelper.requirements.util.*;
import com.questhelper.ItemCollections;

import java.util.*;

public class QuestFromWiki extends BasicQuestHelper {

    // === Step Fields ===
    QuestStep all_settings__disable_levelup;
    QuestStep talk_to;
    QuestStep pickpocket_a_manwoman;
    QuestStep head_northwest_to___drop_air__mind_runes_and_cl;
    QuestStep sell_bronze_dagger_sword_wooden_shield__shortbo;
    QuestStep head_east__start_x_marks_the_spot_on_veos___comp;
    QuestStep check_playtime_on;
    QuestStep go_upstairs_and_talk_to;
    QuestStep go_upstairs_again_and_collect_4x_logs_on_the_top_f;
    QuestStep bank_at_lumbridge_castle_top_floor_and_deposit_all;
    QuestStep keep_the_shrimps_in_your_bank_for_later;
    QuestStep move_coins_into_first_bank_slot__runes_to_the_top;
    QuestStep withdraw_coins_air_runes_mind_runes_bread_spa;
    QuestStep go_down_south_staircase_twice;
    QuestStep collect_the_empty_jug_bowl__knife_in_lumbridge_k;
    QuestStep fill_the_jug__bowl_on_the_sink_in_the_kitchen;
    QuestStep complete_2nd_step_of_x_marks_the_spot;
    QuestStep kill_a_giant_rat_with_wind_strike_and_collect_the_;
    QuestStep head_west_towards_draynor_hugging_the_fence_to_avo;
    QuestStep talk_to__in_the_lumbridge_swamp_for_ghost_speak_am;
    QuestStep take_leather_gloves_on_the_table_inside_his_house_;
    QuestStep head_to_the_wizards_tower;
    QuestStep take_leather_boots_off_the_table__wield;
    QuestStep collect_3x_logs_next_to_the_stairs;
    QuestStep head_to_the_basement__talk_to__to_continue_rune_m;
    QuestStep kill_a_chicken_take_everything_make_sure_you_get;
    QuestStep collect_3x_logs;
    QuestStep return_to_draynor__talk_to__and_obtain_forestry_k;
    QuestStep bank_at_draynor_and_deposit_all;
    QuestStep withdraw_coins_spade_feather__mysterious_orb;
    QuestStep collect_cheese_from;
    QuestStep complete_3rd_step_of_x_marks_the_spot;
    QuestStep talk_to__and_start_vampyre_slayer;
    QuestStep go_up_the_stairs_and_collect_4x_garlic_from_the_cu;
    QuestStep you_can_get_multiple_garlic_by_spamclicking_the_cu;
    QuestStep train_draynor_agility_to_5_agility;
    QuestStep bank_at_draynor_and_deposit_the_garlic__cheese;
    QuestStep talk_to___buy_5_wines_hop_worlds_and_buy_10_in_t;
    QuestStep start;
    QuestStep complete_4th_step_of_x_marks_the_spot;
    QuestStep head_west_to_port_sarim_and_talk_to__to_complete_x;
    QuestStep destroy_the_lamp_you_can_collect_this_later_as_yo;
    QuestStep travel_to_port_piscarilius;
    QuestStep talk_to;
    QuestStep take_minecart_to_shayzien_east;
    QuestStep open_minimap__follow_the_path_southwest_to_shayz;
    QuestStep take_the_beer;
    QuestStep use_your_feather_on_the_enchanted_scroll_in_your_i;
    QuestStep talk_to__for_client_of_kourend;
    QuestStep take_tinderbox;
    QuestStep take_wizard_hat__orange_dye;
    QuestStep buy_chefs_hat;
    QuestStep home_teleport_to_lumbridge;
    QuestStep talk_to__and_buy_a_steel_axe;
    QuestStep talk_to;
    QuestStep talk_to__and_be_teleported_to_stronghold_of_securi;
    QuestStep complete_3_floors_of_stronghold_of_security;
    QuestStep on_floor_3_spider_max_is_7_so_if_you_take_3_or_mo;
    QuestStep max_is_9_so_drink_on_any_damage;
    QuestStep once_you_have_10000gp_from_floor_3_leave_via_the;
    QuestStep collect_3x_beer_inside_the_longhall;
    QuestStep collect_a_cooked_meat;
    QuestStep head_east_and_talk_to;
    QuestStep collect_a_doogle_leaf_south_of_gertrude;
    QuestStep bank_at_varrock_west_bank_and_deposit_all;
    QuestStep withdraw_coins_bones_beer;
    QuestStep use_the_bones_on_the__whenever_you_find_him;
    QuestStep head_east_and_buy_an_air_staff_from__equip_it;
    QuestStep head_south__talk_to__and_start_demon_slayer_;
    QuestStep head_south__trade;
    QuestStep buy_pink_skirt_brown_apron__silk_wear_brown_apr;
    QuestStep head_south_to_the_sword_shop_and_go_up_the_ladder;
    QuestStep head_east_and_talk_to;
    QuestStep head_north;
    QuestStep talk_to;
    QuestStep buy_a_newspaper_from;
    QuestStep talk_to__to_continue_gertrudes_cat;
    QuestStep talk_to;
    QuestStep complete_children_of_the_sun;
    QuestStep talk_to;
    QuestStep head_north_and_go_up_2x_stairs_and_talk_to;
    QuestStep return_down_the_stairs_and_talk_to__and_start_shie;
    QuestStep search_for_book_and_talk_to__again;
    QuestStep head_east_and_up_the_stairs_in_the_kitchen;
    QuestStep collect_both_buckets_and_fill_one_up_downstairs_u;
    QuestStep take_the_pie_dish;
    QuestStep head_to__and_start_priest_in_peril;
    QuestStep talk_to__and_start_daddys_home_in_a_house_the_ea;
    QuestStep pick_up_the_saw;
    QuestStep enter_varrock_sewer_and_take_the_northwest_path_t;
    QuestStep enter_varrock_museum_and_head_downstairs_and_talk_;
    QuestStep bank_at_varrock_east_bank_and_deposit_all;
    QuestStep withdraw_coins_saw_hammer_knife_bronze_axe_r;
    QuestStep talk_to__to_continue_rune_mysteries;
    QuestStep light_both_logs_in_the_house_right_next_to_the_run;
    QuestStep destroy_all_the_furniture_in_the_house;
    QuestStep talk_to__to_continue_daddys_home;
    QuestStep take_2x_logs__2x_ashes_after_cutscene;
    QuestStep search_crates_for_3x_waxwood_log;
    QuestStep bank_the_ashes;
    QuestStep head_northeast_to_the_lumberyard;
    QuestStep cut_the_dying_tree;
    QuestStep collect_the_logs__fletch_2100_arrowshafts_hop_b;
    QuestStep collect_11_logs__make_10_into_planks_make_the_3_;
    QuestStep buy_5x_bolts_of_cloth__100_steel_nails;
    QuestStep return_to___continue_daddys_home;
    QuestStep light_1_log__take_the_1x_log;
    QuestStep collect_ashes;
    QuestStep trade__and_buy_1x_fireairearth_pack_2x_water_pa;
    QuestStep complete_daddys_home_at_marlo;
    QuestStep open_the_crate;
    QuestStep bank_at_varrock_east_bank;
    QuestStep withdraw_leather_gloves_to_pick_nettles;
    QuestStep travel_east_to___travel_to_varlamore;
    QuestStep open_the_minimap_and_head_south_out_of_the_city;
    QuestStep take_the_3x_logs_rope_pestle__mortar__vial_of_;
    QuestStep pick_2_nettles;
    QuestStep collect_1_sweetcorn;
    QuestStep head_west_to_the_hunters_guild;
    QuestStep collect_the_needle;
    QuestStep collect_a_bucket_of_water_by_the_bank_chest;
    QuestStep deposit_all_in_the_bank_chest;
    QuestStep enter_s_building_and_go_up_both_ladders;
    QuestStep loot_28_s_hop_worlds;
    QuestStep deposit_all;
    QuestStep withdraw_coins;
    QuestStep collect_a_bucket_of_water_by_the_bank_chest;
    QuestStep head_southwest_to_sunset_coast_be_careful_of_the;
    QuestStep loot_fly_fishing_rod_lobster_pot_3x_iron_bar_ho;
    QuestStep travel_with__to_aldarin;
    QuestStep take_pot_of_flour;
    QuestStep buy_6_onions;
    QuestStep pick_a_cabbage;
    QuestStep bank_south_and_deposit_all;
    QuestStep withdraw_28x_red_eclipse;
    QuestStep head_west_and_trade__and_sell_all_28_at_once;
    QuestStep head_east_after_selling_eclipse_reds_and_buy_3_s_f;
    QuestStep head_northeast_to_the_gem_store__buy_9x_uncut_sa;
    QuestStep head_south_to___deposit_all_there;
    QuestStep buy_steel_pickaxe_150_wines_20_mindbombs__20_st;
    QuestStep bank_at__and_deposit_all;
    QuestStep withdraw_coins_research_notes_bronze_pickaxe;
    QuestStep home_teleport_to_lumbridge;
    QuestStep head_to_the_wizards_tower;
    QuestStep take_3x_logs;
    QuestStep search_the_altar_to_collect_the_ghosts_skull_run;
    QuestStep complete_rune_mysteries;
    QuestStep teleport_to_rune_essence_mine;
    QuestStep take_3x_logs;
    QuestStep head_north_to_draynor_and_deposit_all;
    QuestStep withdraw_coins_mind_runes_small_fishing_net_on;
    QuestStep buy___10_teleport_cards_from;
    QuestStep use_pages_on_chronicle_and_wield;
    QuestStep head_west_and_talk_to__to_start_pirates_treasure;
    QuestStep head_southwest_and_buy_a_harpoon_50_bait__10_fe;
    QuestStep make_454_headless_arrows;
    QuestStep take_ship_to_karamja_seamen_dressed_in_blue;
    QuestStep talk_to__and_ask_for_employment;
    QuestStep fish_raw_shrimps_karamja_easy_diary_drop_shrimps;
    QuestStep pick_10_bananas;
    QuestStep buy_karamja_rum;
    QuestStep fill_crate_with_bananas_and_use_karamja_rum_on_the;
    QuestStep take_boat_back_to_port_sarim;
    QuestStep trade_wydin_and_buy_raw_chicken_2x_raw_beef_3x_f;
    QuestStep continue_pirates_treasure_by_talking_to_wydin_to_;
    QuestStep buy_8x_raw_sardines;
    QuestStep use_the_deposit_box_by_entrana_and_deposit_everyth;
    QuestStep return_to;
    QuestStep head_west_to_betty_and_buy_2x_eye_of_newt__200_mi;
    QuestStep head_southwest_and_complete_witches_potion_beef_;
    QuestStep take_2x_logs_when_getting_the_rat_tail;
    QuestStep buy_moulds_ring_amulet_2x_necklace_bracelet_s;
    QuestStep buy_3x_buckets__shears;
    QuestStep head_northwest_and_collect_a_snape_grass;
    QuestStep milk_the_cow_3x_by_crafting_guild;
    QuestStep kill_a_cow__take_everything;
    QuestStep shear_a_sheep_by_the_makeover_mage;
    QuestStep take_falador_crumbling_wall_shortcut;
    QuestStep bank_at_falador_west_bank_and_deposit_all;
    QuestStep withdraw_coins_mind_runes_raw_ratchickenbeef;
    QuestStep get_a_haircut_north;
    QuestStep fill_bucket_on_pump;
    QuestStep head_south_and_talk_to_the__and_start_knights_swo;
    QuestStep get_a_mahogany_home_beginner_contract_from__try_a;
    QuestStep kill_a_duck_in_falador_park;
    QuestStep buy_6x_woad_leaves_from;
    QuestStep head_north_of_falador_and_kill_a_black_bear_safes;
    QuestStep head_to_taverly_and_talk_to_the__to_start_witches_;
    QuestStep head_north_and_talk_to__to_start_druidic_ritual;

    // === Item Requirements ===
    ItemRequirement 1sweetcorn;
    ItemRequirement 10xwines;
    ItemRequirement 11logs;
    ItemRequirement 1xlog;
    ItemRequirement 28xredeclipse;
    ItemRequirement 2xeyeofnewt;
    ItemRequirement 2xlogs;
    ItemRequirement 2xwines8inventoryslots;
    ItemRequirement 3xbuckets;
    ItemRequirement 3xlogs;
    ItemRequirement 454arrowshafts;
    ItemRequirement 5xboltsofcloth;
    ItemRequirement 6onions;
    ItemRequirement 6xwoadleavesfrom;
    ItemRequirement 8xrawsardines;
    ItemRequirement airrunes;
    ItemRequirement airtalisman;
    ItemRequirement ashes;
    ItemRequirement beef;
    ItemRequirement beer;
    ItemRequirement beer3inventoryspaces;
    ItemRequirement bones;
    ItemRequirement bread;
    ItemRequirement bronzeaxe;
    ItemRequirement bronzedagger;
    ItemRequirement bronzepickaxe3inventoryslots;
    ItemRequirement brownapron;
    ItemRequirement bucketofwaterbythebankchest;
    ItemRequirement cheese18inventoryslots;
    ItemRequirement cheesefrom;
    ItemRequirement chefshat;
    ItemRequirement chestkey;
    ItemRequirement chicken;
    ItemRequirement coins;
    ItemRequirement cookedmeat;
    ItemRequirement emptybucket;
    ItemRequirement emptyjug;
    ItemRequirement feather;
    ItemRequirement hammer;
    ItemRequirement harpoon;
    ItemRequirement karamjarum;
    ItemRequirement knife;
    ItemRequirement leatherbootsoffthetable;
    ItemRequirement leatherglovestopicknettles;
    ItemRequirement logs;
    ItemRequirement mindrunes;
    ItemRequirement mysteriousorb4inventoryslots;
    ItemRequirement newspaperfrom;
    ItemRequirement onion;
    ItemRequirement pickaxe;
    ItemRequirement piedish;
    ItemRequirement pinkskirt;
    ItemRequirement potofflour;
    ItemRequirement rawbearmeat;
    ItemRequirement rawchicken;
    ItemRequirement rawrat;
    ItemRequirement researchnotes;
    ItemRequirement researchpackage;
    ItemRequirement saw;
    ItemRequirement smallfishingnet;
    ItemRequirement snapegrass;
    ItemRequirement spade;
    ItemRequirement spadechisel;
    ItemRequirement steelpickaxe;
    ItemRequirement tinderbox;
    ItemRequirement tinderbox7inventoryslots;
    ItemRequirement treasurescroll8inventoryslots;
    ItemRequirement wizardhat;
    ItemRequirement bothbuckets;
    ItemRequirement employed;
    ItemRequirement haircutnorth;
    ItemRequirement here;
    ItemRequirement lamp;
    ItemRequirement moulds;
    ItemRequirement needle;
    ItemRequirement rumfromthecrate;

    @Override
    public Map<Integer, QuestStep> loadSteps()
    {
        Map<Integer, QuestStep> steps = new HashMap<>();
        int idx = 0;

        steps.put(idx++, all_settings__disable_levelup);
        steps.put(idx++, talk_to);
        steps.put(idx++, pickpocket_a_manwoman);
        steps.put(idx++, head_northwest_to___drop_air__mind_runes_and_cl);
        steps.put(idx++, sell_bronze_dagger_sword_wooden_shield__shortbo);
        steps.put(idx++, head_east__start_x_marks_the_spot_on_veos___comp);
        steps.put(idx++, check_playtime_on);
        steps.put(idx++, go_upstairs_and_talk_to);
        steps.put(idx++, go_upstairs_again_and_collect_4x_logs_on_the_top_f);
        steps.put(idx++, bank_at_lumbridge_castle_top_floor_and_deposit_all);
        steps.put(idx++, keep_the_shrimps_in_your_bank_for_later);
        steps.put(idx++, move_coins_into_first_bank_slot__runes_to_the_top);
        steps.put(idx++, withdraw_coins_air_runes_mind_runes_bread_spa);
        steps.put(idx++, go_down_south_staircase_twice);
        steps.put(idx++, collect_the_empty_jug_bowl__knife_in_lumbridge_k);
        steps.put(idx++, fill_the_jug__bowl_on_the_sink_in_the_kitchen);
        steps.put(idx++, complete_2nd_step_of_x_marks_the_spot);
        steps.put(idx++, kill_a_giant_rat_with_wind_strike_and_collect_the_);
        steps.put(idx++, head_west_towards_draynor_hugging_the_fence_to_avo);
        steps.put(idx++, talk_to__in_the_lumbridge_swamp_for_ghost_speak_am);
        steps.put(idx++, take_leather_gloves_on_the_table_inside_his_house_);
        steps.put(idx++, head_to_the_wizards_tower);
        steps.put(idx++, take_leather_boots_off_the_table__wield);
        steps.put(idx++, collect_3x_logs_next_to_the_stairs);
        steps.put(idx++, head_to_the_basement__talk_to__to_continue_rune_m);
        steps.put(idx++, kill_a_chicken_take_everything_make_sure_you_get);
        steps.put(idx++, collect_3x_logs);
        steps.put(idx++, return_to_draynor__talk_to__and_obtain_forestry_k);
        steps.put(idx++, bank_at_draynor_and_deposit_all);
        steps.put(idx++, withdraw_coins_spade_feather__mysterious_orb);
        steps.put(idx++, collect_cheese_from);
        steps.put(idx++, complete_3rd_step_of_x_marks_the_spot);
        steps.put(idx++, talk_to__and_start_vampyre_slayer);
        steps.put(idx++, go_up_the_stairs_and_collect_4x_garlic_from_the_cu);
        steps.put(idx++, you_can_get_multiple_garlic_by_spamclicking_the_cu);
        steps.put(idx++, train_draynor_agility_to_5_agility);
        steps.put(idx++, bank_at_draynor_and_deposit_the_garlic__cheese);
        steps.put(idx++, talk_to___buy_5_wines_hop_worlds_and_buy_10_in_t);
        steps.put(idx++, start);
        steps.put(idx++, complete_4th_step_of_x_marks_the_spot);
        steps.put(idx++, head_west_to_port_sarim_and_talk_to__to_complete_x);
        steps.put(idx++, destroy_the_lamp_you_can_collect_this_later_as_yo);
        steps.put(idx++, travel_to_port_piscarilius);
        steps.put(idx++, talk_to);
        steps.put(idx++, take_minecart_to_shayzien_east);
        steps.put(idx++, open_minimap__follow_the_path_southwest_to_shayz);
        steps.put(idx++, take_the_beer);
        steps.put(idx++, use_your_feather_on_the_enchanted_scroll_in_your_i);
        steps.put(idx++, talk_to__for_client_of_kourend);
        steps.put(idx++, take_tinderbox);
        steps.put(idx++, take_wizard_hat__orange_dye);
        steps.put(idx++, buy_chefs_hat);
        steps.put(idx++, home_teleport_to_lumbridge);
        steps.put(idx++, talk_to__and_buy_a_steel_axe);
        steps.put(idx++, talk_to);
        steps.put(idx++, talk_to__and_be_teleported_to_stronghold_of_securi);
        steps.put(idx++, complete_3_floors_of_stronghold_of_security);
        steps.put(idx++, on_floor_3_spider_max_is_7_so_if_you_take_3_or_mo);
        steps.put(idx++, max_is_9_so_drink_on_any_damage);
        steps.put(idx++, once_you_have_10000gp_from_floor_3_leave_via_the);
        steps.put(idx++, collect_3x_beer_inside_the_longhall);
        steps.put(idx++, collect_a_cooked_meat);
        steps.put(idx++, head_east_and_talk_to);
        steps.put(idx++, collect_a_doogle_leaf_south_of_gertrude);
        steps.put(idx++, bank_at_varrock_west_bank_and_deposit_all);
        steps.put(idx++, withdraw_coins_bones_beer);
        steps.put(idx++, use_the_bones_on_the__whenever_you_find_him);
        steps.put(idx++, head_east_and_buy_an_air_staff_from__equip_it);
        steps.put(idx++, head_south__talk_to__and_start_demon_slayer_);
        steps.put(idx++, head_south__trade);
        steps.put(idx++, buy_pink_skirt_brown_apron__silk_wear_brown_apr);
        steps.put(idx++, head_south_to_the_sword_shop_and_go_up_the_ladder);
        steps.put(idx++, head_east_and_talk_to);
        steps.put(idx++, head_north);
        steps.put(idx++, talk_to);
        steps.put(idx++, buy_a_newspaper_from);
        steps.put(idx++, talk_to__to_continue_gertrudes_cat);
        steps.put(idx++, talk_to);
        steps.put(idx++, complete_children_of_the_sun);
        steps.put(idx++, talk_to);
        steps.put(idx++, head_north_and_go_up_2x_stairs_and_talk_to);
        steps.put(idx++, return_down_the_stairs_and_talk_to__and_start_shie);
        steps.put(idx++, search_for_book_and_talk_to__again);
        steps.put(idx++, head_east_and_up_the_stairs_in_the_kitchen);
        steps.put(idx++, collect_both_buckets_and_fill_one_up_downstairs_u);
        steps.put(idx++, take_the_pie_dish);
        steps.put(idx++, head_to__and_start_priest_in_peril);
        steps.put(idx++, talk_to__and_start_daddys_home_in_a_house_the_ea);
        steps.put(idx++, pick_up_the_saw);
        steps.put(idx++, enter_varrock_sewer_and_take_the_northwest_path_t);
        steps.put(idx++, enter_varrock_museum_and_head_downstairs_and_talk_);
        steps.put(idx++, bank_at_varrock_east_bank_and_deposit_all);
        steps.put(idx++, withdraw_coins_saw_hammer_knife_bronze_axe_r);
        steps.put(idx++, talk_to__to_continue_rune_mysteries);
        steps.put(idx++, light_both_logs_in_the_house_right_next_to_the_run);
        steps.put(idx++, destroy_all_the_furniture_in_the_house);
        steps.put(idx++, talk_to__to_continue_daddys_home);
        steps.put(idx++, take_2x_logs__2x_ashes_after_cutscene);
        steps.put(idx++, search_crates_for_3x_waxwood_log);
        steps.put(idx++, bank_the_ashes);
        steps.put(idx++, head_northeast_to_the_lumberyard);
        steps.put(idx++, cut_the_dying_tree);
        steps.put(idx++, collect_the_logs__fletch_2100_arrowshafts_hop_b);
        steps.put(idx++, collect_11_logs__make_10_into_planks_make_the_3_);
        steps.put(idx++, buy_5x_bolts_of_cloth__100_steel_nails);
        steps.put(idx++, return_to___continue_daddys_home);
        steps.put(idx++, light_1_log__take_the_1x_log);
        steps.put(idx++, collect_ashes);
        steps.put(idx++, trade__and_buy_1x_fireairearth_pack_2x_water_pa);
        steps.put(idx++, complete_daddys_home_at_marlo);
        steps.put(idx++, open_the_crate);
        steps.put(idx++, bank_at_varrock_east_bank);
        steps.put(idx++, withdraw_leather_gloves_to_pick_nettles);
        steps.put(idx++, travel_east_to___travel_to_varlamore);
        steps.put(idx++, open_the_minimap_and_head_south_out_of_the_city);
        steps.put(idx++, take_the_3x_logs_rope_pestle__mortar__vial_of_);
        steps.put(idx++, pick_2_nettles);
        steps.put(idx++, collect_1_sweetcorn);
        steps.put(idx++, head_west_to_the_hunters_guild);
        steps.put(idx++, collect_the_needle);
        steps.put(idx++, collect_a_bucket_of_water_by_the_bank_chest);
        steps.put(idx++, deposit_all_in_the_bank_chest);
        steps.put(idx++, enter_s_building_and_go_up_both_ladders);
        steps.put(idx++, loot_28_s_hop_worlds);
        steps.put(idx++, deposit_all);
        steps.put(idx++, withdraw_coins);
        steps.put(idx++, collect_a_bucket_of_water_by_the_bank_chest);
        steps.put(idx++, head_southwest_to_sunset_coast_be_careful_of_the);
        steps.put(idx++, loot_fly_fishing_rod_lobster_pot_3x_iron_bar_ho);
        steps.put(idx++, travel_with__to_aldarin);
        steps.put(idx++, take_pot_of_flour);
        steps.put(idx++, buy_6_onions);
        steps.put(idx++, pick_a_cabbage);
        steps.put(idx++, bank_south_and_deposit_all);
        steps.put(idx++, withdraw_28x_red_eclipse);
        steps.put(idx++, head_west_and_trade__and_sell_all_28_at_once);
        steps.put(idx++, head_east_after_selling_eclipse_reds_and_buy_3_s_f);
        steps.put(idx++, head_northeast_to_the_gem_store__buy_9x_uncut_sa);
        steps.put(idx++, head_south_to___deposit_all_there);
        steps.put(idx++, buy_steel_pickaxe_150_wines_20_mindbombs__20_st);
        steps.put(idx++, bank_at__and_deposit_all);
        steps.put(idx++, withdraw_coins_research_notes_bronze_pickaxe);
        steps.put(idx++, home_teleport_to_lumbridge);
        steps.put(idx++, head_to_the_wizards_tower);
        steps.put(idx++, take_3x_logs);
        steps.put(idx++, search_the_altar_to_collect_the_ghosts_skull_run);
        steps.put(idx++, complete_rune_mysteries);
        steps.put(idx++, teleport_to_rune_essence_mine);
        steps.put(idx++, take_3x_logs);
        steps.put(idx++, head_north_to_draynor_and_deposit_all);
        steps.put(idx++, withdraw_coins_mind_runes_small_fishing_net_on);
        steps.put(idx++, buy___10_teleport_cards_from);
        steps.put(idx++, use_pages_on_chronicle_and_wield);
        steps.put(idx++, head_west_and_talk_to__to_start_pirates_treasure);
        steps.put(idx++, head_southwest_and_buy_a_harpoon_50_bait__10_fe);
        steps.put(idx++, make_454_headless_arrows);
        steps.put(idx++, take_ship_to_karamja_seamen_dressed_in_blue);
        steps.put(idx++, talk_to__and_ask_for_employment);
        steps.put(idx++, fish_raw_shrimps_karamja_easy_diary_drop_shrimps);
        steps.put(idx++, pick_10_bananas);
        steps.put(idx++, buy_karamja_rum);
        steps.put(idx++, fill_crate_with_bananas_and_use_karamja_rum_on_the);
        steps.put(idx++, take_boat_back_to_port_sarim);
        steps.put(idx++, trade_wydin_and_buy_raw_chicken_2x_raw_beef_3x_f);
        steps.put(idx++, continue_pirates_treasure_by_talking_to_wydin_to_);
        steps.put(idx++, buy_8x_raw_sardines);
        steps.put(idx++, use_the_deposit_box_by_entrana_and_deposit_everyth);
        steps.put(idx++, return_to);
        steps.put(idx++, head_west_to_betty_and_buy_2x_eye_of_newt__200_mi);
        steps.put(idx++, head_southwest_and_complete_witches_potion_beef_);
        steps.put(idx++, take_2x_logs_when_getting_the_rat_tail);
        steps.put(idx++, buy_moulds_ring_amulet_2x_necklace_bracelet_s);
        steps.put(idx++, buy_3x_buckets__shears);
        steps.put(idx++, head_northwest_and_collect_a_snape_grass);
        steps.put(idx++, milk_the_cow_3x_by_crafting_guild);
        steps.put(idx++, kill_a_cow__take_everything);
        steps.put(idx++, shear_a_sheep_by_the_makeover_mage);
        steps.put(idx++, take_falador_crumbling_wall_shortcut);
        steps.put(idx++, bank_at_falador_west_bank_and_deposit_all);
        steps.put(idx++, withdraw_coins_mind_runes_raw_ratchickenbeef);
        steps.put(idx++, get_a_haircut_north);
        steps.put(idx++, fill_bucket_on_pump);
        steps.put(idx++, head_south_and_talk_to_the__and_start_knights_swo);
        steps.put(idx++, get_a_mahogany_home_beginner_contract_from__try_a);
        steps.put(idx++, kill_a_duck_in_falador_park);
        steps.put(idx++, buy_6x_woad_leaves_from);
        steps.put(idx++, head_north_of_falador_and_kill_a_black_bear_safes);
        steps.put(idx++, head_to_taverly_and_talk_to_the__to_start_witches_);
        steps.put(idx++, head_north_and_talk_to__to_start_druidic_ritual);

        return steps;
    }

    @Override
    public void setupRequirements()
    {

    }

    @Override
    public void setupZones()
    {
        // Define zones if needed
    }

    @Override
    public void setupConditions()
    {
        // Define conditions if needed
    }

    @Override
    public void setupSteps()
    {

        all_settings__disable_levelup = new DetailedQuestStep(this, "All Settings -> Disable level-up");
        talk_to = new NpcStep(this, NpcID.FATHER_AERECK, new WorldPoint(3243, 3206, 0), "Talk to");
        talk_to.addDialogSteps("3", "1");
        pickpocket_a_manwoman = new NpcStep(this, NpcID.WOMAN, new WorldPoint(3224, 3218, 0), "Pickpocket a man/woman");
        head_northwest_to___drop_air__mind_runes_and_cl = new DetailedQuestStep(this, "Head North-West to  & drop Air & Mind Runes and claim more.");
        sell_bronze_dagger_sword_wooden_shield__shortbo = new DetailedQuestStep(this, "Sell Bronze Dagger, Sword, Wooden Shield & Shortbow to General Store. Buy a Spade Chisel & hammer");
        head_east__start_x_marks_the_spot_on_veos___comp = new DetailedQuestStep(this, "Head East & Start X Marks the Spot on Veos  & complete the first step (Install Quest Helper plug in on Runelite)");
        check_playtime_on = new NpcStep(this, NpcID.HANS, new WorldPoint(3215, 3219, 0), "Check playtime on");
        go_upstairs_and_talk_to = new NpcStep(this, NpcID.DUKE_HORACIO, new WorldPoint(3210, 3222, 1), "Go upstairs and Talk to");
        go_upstairs_and_talk_to.addDialogSteps("1", "1");
        go_upstairs_again_and_collect_4x_logs_on_the_top_f = new DetailedQuestStep(this, "Go upstairs again and Collect 4x logs on the top floor");
        bank_at_lumbridge_castle_top_floor_and_deposit_all = new DetailedQuestStep(this, "Bank at Lumbridge castle top floor and deposit all");
        keep_the_shrimps_in_your_bank_for_later = new DetailedQuestStep(this, "Keep the Shrimps in your bank for later");
        move_coins_into_first_bank_slot__runes_to_the_top = new DetailedQuestStep(this, "Move Coins into first bank slot & Runes to the top slots. Click the lock to Always set Placeholders. Set Bank pin for Count Check randoms or delete the pin from Tutorial Island.");
        withdraw_coins_air_runes_mind_runes_bread_spa = new DetailedQuestStep(this, "Withdraw: Coins, Air Runes, Mind Runes, Bread, Spade, Tinderbox, Air Talisman, Treasure Scroll");
        go_down_south_staircase_twice = new DetailedQuestStep(this, "Go down south staircase twice");
        collect_the_empty_jug_bowl__knife_in_lumbridge_k = new DetailedQuestStep(this, "Collect the Empty Jug, Bowl & Knife in Lumbridge kitchen");
        fill_the_jug__bowl_on_the_sink_in_the_kitchen = new ObjectStep(this, ObjectID.JUG, new WorldPoint(1445, 9336, 0), "Fill the jug & bowl on the sink in the kitchen");
        complete_2nd_step_of_x_marks_the_spot = new DetailedQuestStep(this, "Complete 2nd Step of X Marks The Spot");
        kill_a_giant_rat_with_wind_strike_and_collect_the_ = new DetailedQuestStep(this, "Kill a giant rat with Wind Strike and collect the Bones + Raw Rat Meat");
        head_west_towards_draynor_hugging_the_fence_to_avo = new DetailedQuestStep(this, "Head West towards Draynor hugging the fence to avoid the Jail Guards");
        talk_to__in_the_lumbridge_swamp_for_ghost_speak_am = new NpcStep(this, NpcID.FATHER_URHNEY, new WorldPoint(3147, 3175, 0), "Talk to  in the lumbridge swamp for Ghost Speak Amulet.  Wield this.");
        talk_to__in_the_lumbridge_swamp_for_ghost_speak_am.addDialogSteps("2", "1");
        take_leather_gloves_on_the_table_inside_his_house_ = new DetailedQuestStep(this, "Take Leather Gloves on the table inside his house & wield");
        head_to_the_wizards_tower = new DetailedQuestStep(this, "Head to the Wizards Tower");
        take_leather_boots_off_the_table__wield = new DetailedQuestStep(this, "Take Leather Boots off the table & wield");
        collect_3x_logs_next_to_the_stairs = new DetailedQuestStep(this, "Collect 3x Logs next to the stairs");
        head_to_the_basement__talk_to__to_continue_rune_m = new DetailedQuestStep(this, "Head to the basement & Talk to  to continue Rune Mysteries");
        kill_a_chicken_take_everything_make_sure_you_get = new DetailedQuestStep(this, "Kill a Chicken. Take Everything (Make sure you get a feather, else hop worlds and repeat)");
        collect_3x_logs = new DetailedQuestStep(this, "Collect 3x Logs");
        return_to_draynor__talk_to__and_obtain_forestry_k = new DetailedQuestStep(this, "Return to Draynor & talk to  and obtain Forestry kit (right click shop and buy 1)");
        bank_at_draynor_and_deposit_all = new DetailedQuestStep(this, "Bank at Draynor and Deposit all");
        withdraw_coins_spade_feather__mysterious_orb = new DetailedQuestStep(this, "Withdraw: Coins, Spade, Feather & Mysterious Orb");
        collect_cheese_from = new DetailedQuestStep(this, "Collect Cheese from");
        complete_3rd_step_of_x_marks_the_spot = new DetailedQuestStep(this, "Complete 3rd Step of X Marks the Spot");
        talk_to__and_start_vampyre_slayer = new NpcStep(this, NpcID.MORGAN, new WorldPoint(3098, 3268, 0), "Talk to  and start Vampyre Slayer");
        talk_to__and_start_vampyre_slayer.addDialogSteps("1");
        go_up_the_stairs_and_collect_4x_garlic_from_the_cu = new DetailedQuestStep(this, "Go up the stairs and collect 4x Garlic from the cupboard");
        you_can_get_multiple_garlic_by_spamclicking_the_cu = new DetailedQuestStep(this, "You can get multiple garlic by spamclicking the cupboard");
        train_draynor_agility_to_5_agility = new DetailedQuestStep(this, "Train Draynor Agility to 5 Agility");
        bank_at_draynor_and_deposit_the_garlic__cheese = new DetailedQuestStep(this, "Bank at Draynor and deposit the Garlic & cheese");
        talk_to___buy_5_wines_hop_worlds_and_buy_10_in_t = new NpcStep(this, NpcID.FORTUNATO, new WorldPoint(3085, 3251, 0), "Talk to  & buy 5 wines. Hop worlds and buy 10 in total.");
        start = new DetailedQuestStep(this, "Start");
        complete_4th_step_of_x_marks_the_spot = new DetailedQuestStep(this, "Complete 4th Step of X Marks the Spot");
        head_west_to_port_sarim_and_talk_to__to_complete_x = new NpcStep(this, NpcID.VEOS, new WorldPoint(3228, 3242, 0), "Head West to Port Sarim and talk to  to complete X Marks The Spot.");
        destroy_the_lamp_you_can_collect_this_later_as_yo = new DetailedQuestStep(this, "Destroy the lamp. You can collect this later as you can't bank it.");
        travel_to_port_piscarilius = new DetailedQuestStep(this, "Travel to Port Piscarilius");
        talk_to = new NpcStep(this, NpcID.VEOS, new WorldPoint(3228, 3242, 0), "Talk to");
        talk_to.addDialogSteps("4", "1");
        take_minecart_to_shayzien_east = new DetailedQuestStep(this, "Take Minecart to Shayzien East");
        open_minimap__follow_the_path_southwest_to_shayz = new DetailedQuestStep(this, "Open Minimap & follow the path South-West to Shayzien");
        take_the_beer = new DetailedQuestStep(this, "Take the Beer");
        use_your_feather_on_the_enchanted_scroll_in_your_i = new DetailedQuestStep(this, "Use your feather on the enchanted scroll in your inventory");
        talk_to__for_client_of_kourend = new DetailedQuestStep(this, "Talk to  for Client of Kourend");
        take_tinderbox = new DetailedQuestStep(this, "Take Tinderbox");
        take_wizard_hat__orange_dye = new DetailedQuestStep(this, "Take Wizard Hat & Orange Dye");
        buy_chefs_hat = new DetailedQuestStep(this, "Buy Chefs Hat");
        home_teleport_to_lumbridge = new DetailedQuestStep(this, "Home teleport to Lumbridge");
        talk_to__and_buy_a_steel_axe = new NpcStep(this, NpcID.BOB, new WorldPoint(2748, 3559, 0), "Talk to  and buy a Steel Axe");
        talk_to = new NpcStep(this, NpcID.RESTLESS_GHOST, new WorldPoint(3250, 3195, 0), "Talk to");
        talk_to.addDialogSteps("1");
        talk_to__and_be_teleported_to_stronghold_of_securi = new NpcStep(this, NpcID.COUNT_CHECK, new WorldPoint(3238, 3199, 0), "Talk to  and be teleported to Stronghold of Security");
        talk_to__and_be_teleported_to_stronghold_of_securi.addDialogSteps("3", "1");
        complete_3_floors_of_stronghold_of_security = new DetailedQuestStep(this, "Complete 3 Floors of Stronghold of Security.");
        on_floor_3_spider_max_is_7_so_if_you_take_3_or_mo = new DetailedQuestStep(this, "On Floor 3, Spider max is 7 so if you take 3 or more damage, drink a wine before going through the door to avoid being stacked. Take the east doors.");
        max_is_9_so_drink_on_any_damage = new NpcStep(this, NpcID.CATABLEPON, new WorldPoint(2144, 5281, 0), "Max is 9 so drink on any damage.");
        once_you_have_10000gp_from_floor_3_leave_via_the = new DetailedQuestStep(this, "Once you have 10,000GP from Floor 3, leave via the ropes");
        collect_3x_beer_inside_the_longhall = new DetailedQuestStep(this, "Collect 3x Beer inside the Longhall");
        collect_a_cooked_meat = new DetailedQuestStep(this, "Collect a Cooked Meat");
        head_east_and_talk_to = new NpcStep(this, NpcID.GERTRUDE, new WorldPoint(3151, 3415, 0), "Head east and Talk to");
        head_east_and_talk_to.addDialogSteps("1");
        collect_a_doogle_leaf_south_of_gertrude = new DetailedQuestStep(this, "Collect a Doogle Leaf south of Gertrude");
        bank_at_varrock_west_bank_and_deposit_all = new DetailedQuestStep(this, "Bank at Varrock West Bank and deposit all");
        withdraw_coins_bones_beer = new DetailedQuestStep(this, "Withdraw: Coins, Bones, Beer");
        use_the_bones_on_the__whenever_you_find_him = new DetailedQuestStep(this, "Use the bones on the  whenever you find him");
        head_east_and_buy_an_air_staff_from__equip_it = new NpcStep(this, NpcID.ZAFF, new WorldPoint(3202, 3434, 0), "Head East and buy an Air Staff from . Equip it.");
        head_south__talk_to__and_start_demon_slayer_ = new NpcStep(this, NpcID.ARIS, new WorldPoint(3204, 3424, 0), "Head South & Talk to  and start Demon Slayer .");
        head_south__talk_to__and_start_demon_slayer_.addDialogSteps("1", "2", "3", "4");
        head_south__trade = new NpcStep(this, NpcID.THESSALIA, new WorldPoint(3206, 3417, 0), "Head South & Trade");
        buy_pink_skirt_brown_apron__silk_wear_brown_apr = new DetailedQuestStep(this, "Buy Pink Skirt, Brown Apron & Silk. Wear Brown Apron & Pink Skirt in honour of Faux");
        head_south_to_the_sword_shop_and_go_up_the_ladder = new DetailedQuestStep(this, "Head South to the Sword Shop and go up the ladder. Loot the lit candle.");
        head_east_and_talk_to = new NpcStep(this, NpcID.DR_HARLOW, new WorldPoint(3222, 3399, 0), "Head East and talk to");
        head_north = new DetailedQuestStep(this, "Head North");
        talk_to = new NpcStep(this, NpcID.ROMEO, new WorldPoint(3915, 4900, 0), "Talk to");
        talk_to.addDialogSteps("3", "1");
        buy_a_newspaper_from = new DetailedQuestStep(this, "Buy a Newspaper from");
        talk_to__to_continue_gertrudes_cat = new NpcStep(this, NpcID.SHILOP, new WorldPoint(3222, 3435, 0), "Talk to  to continue Gertrudes Cat");
        talk_to__to_continue_gertrudes_cat.addDialogSteps("2", "2");
        talk_to = new DetailedQuestStep(this, "Talk to");
        complete_children_of_the_sun = new DetailedQuestStep(this, "Complete Children of the Sun");
        talk_to = new NpcStep(this, NpcID.SIR_PRYSIN, new WorldPoint(3908, 4944, 0), "Talk to");
        talk_to.addDialogSteps("3", "1", "2", "2", "1", "1");
        head_north_and_go_up_2x_stairs_and_talk_to = new NpcStep(this, NpcID.CAPTAIN_ROVIN, new WorldPoint(3205, 3498, 2), "Head North and go up 2x Stairs and talk to");
        head_north_and_go_up_2x_stairs_and_talk_to.addDialogSteps("3", "1", "2", "2", "3", "1");
        return_down_the_stairs_and_talk_to__and_start_shie = new NpcStep(this, NpcID.RELDO, new WorldPoint(3914, 4966, 0), "Return down the stairs and talk to  and start Shield of Arrav .");
        return_down_the_stairs_and_talk_to__and_start_shie.addDialogSteps("1", "1");
        search_for_book_and_talk_to__again = new DetailedQuestStep(this, "Search for book and talk to  again");
        head_east_and_up_the_stairs_in_the_kitchen = new DetailedQuestStep(this, "Head East and up the stairs in the Kitchen.");
        collect_both_buckets_and_fill_one_up_downstairs_u = new DetailedQuestStep(this, "Collect both buckets and fill one up downstairs. Use Bucket of Water on drain outside then refill it.");
        take_the_pie_dish = new DetailedQuestStep(this, "Take the Pie Dish");
        head_to__and_start_priest_in_peril = new DetailedQuestStep(this, "Head to  and start Priest in Peril");
        talk_to__and_start_daddys_home_in_a_house_the_ea = new NpcStep(this, NpcID.MARLO, new WorldPoint(3241, 3471, 0), "Talk to  and start Daddy's Home (in a house the east of the castle)");
        talk_to__and_start_daddys_home_in_a_house_the_ea.addDialogSteps("2", "3", "3");
        pick_up_the_saw = new DetailedQuestStep(this, "Pick up the Saw");
        enter_varrock_sewer_and_take_the_northwest_path_t = new DetailedQuestStep(this, "Enter Varrock Sewer and take the North-West path to collect the Demon Slayer Key");
        enter_varrock_museum_and_head_downstairs_and_talk_ = new DetailedQuestStep(this, "Enter Varrock Museum and head downstairs and talk to   and complete the  for 9 slayer and hunter and 28 kudos.");
        bank_at_varrock_east_bank_and_deposit_all = new DetailedQuestStep(this, "Bank at Varrock East bank and Deposit all");
        withdraw_coins_saw_hammer_knife_bronze_axe_r = new DetailedQuestStep(this, "Withdraw: Coins, Saw, Hammer, Knife, Bronze Axe, Research Package, Tinderbox");
        talk_to__to_continue_rune_mysteries = new NpcStep(this, NpcID.AUBURY, new WorldPoint(3253, 3401, 0), "Talk to  to continue Rune Mysteries");
        talk_to__to_continue_rune_mysteries.addDialogSteps("2");
        light_both_logs_in_the_house_right_next_to_the_run = new DetailedQuestStep(this, "Light both logs in the house right next to the rune shop.");
        destroy_all_the_furniture_in_the_house = new DetailedQuestStep(this, "Destroy all the furniture in the house");
        talk_to__to_continue_daddys_home = new NpcStep(this, NpcID.OLD_MAN_YARLO, new WorldPoint(3240, 3395, 0), "Talk to  to continue Daddy's Home");
        talk_to__to_continue_daddys_home.addDialogSteps("2");
        take_2x_logs__2x_ashes_after_cutscene = new DetailedQuestStep(this, "Take 2x Logs & 2x ashes after cutscene");
        search_crates_for_3x_waxwood_log = new DetailedQuestStep(this, "Search crates for 3x Waxwood log");
        bank_the_ashes = new DetailedQuestStep(this, "Bank the ashes");
        head_northeast_to_the_lumberyard = new DetailedQuestStep(this, "Head North-East to the Lumberyard");
        cut_the_dying_tree = new DetailedQuestStep(this, "Cut the Dying tree");
        collect_the_logs__fletch_2100_arrowshafts_hop_b = new DetailedQuestStep(this, "Collect the Logs & fletch 2,100 Arrowshafts (hop between 2 worlds)");
        collect_11_logs__make_10_into_planks_make_the_3_ = new DetailedQuestStep(this, "Collect 11 Logs & make 10 into Planks. Make the 3 Waxwood Planks.");
        buy_5x_bolts_of_cloth__100_steel_nails = new DetailedQuestStep(this, "Buy 5x Bolts of Cloth & 100 Steel Nails");
        return_to___continue_daddys_home = new NpcStep(this, NpcID.OLD_MAN_YARLO, new WorldPoint(3240, 3395, 0), "Return to  & continue Daddy's Home");
        light_1_log__take_the_1x_log = new DetailedQuestStep(this, "Light 1 log & take the 1x log");
        collect_ashes = new DetailedQuestStep(this, "Collect Ashes");
        trade__and_buy_1x_fireairearth_pack_2x_water_pa = new NpcStep(this, NpcID.AUBURY, new WorldPoint(3253, 3401, 0), "Trade  and buy 1x Fire/Air/Earth Pack, 2x Water Pack, 3x Mind Pack");
        complete_daddys_home_at_marlo = new DetailedQuestStep(this, "Complete Daddy's home at Marlo");
        open_the_crate = new ObjectStep(this, ObjectID.CRATE, new WorldPoint(2943, 3151, 0), "Open the crate");
        bank_at_varrock_east_bank = new DetailedQuestStep(this, "Bank at Varrock East bank");
        withdraw_leather_gloves_to_pick_nettles = new DetailedQuestStep(this, "Withdraw: Leather Gloves (to pick nettles)");
        travel_east_to___travel_to_varlamore = new NpcStep(this, NpcID.REGULUS_CENTO, new WorldPoint(3281, 3413, 0), "Travel east to  & travel to Varlamore");
        open_the_minimap_and_head_south_out_of_the_city = new DetailedQuestStep(this, "Open the Minimap and Head South out of the City");
        take_the_3x_logs_rope_pestle__mortar__vial_of_ = new DetailedQuestStep(this, "Take the 3x Logs, Rope, Pestle & Mortar & Vial of Water");
        pick_2_nettles = new DetailedQuestStep(this, "Pick 2 Nettles");
        collect_1_sweetcorn = new DetailedQuestStep(this, "Collect 1 Sweetcorn");
        head_west_to_the_hunters_guild = new DetailedQuestStep(this, "Head West to the Hunter's Guild");
        collect_the_needle = new DetailedQuestStep(this, "Collect the needle");
        collect_a_bucket_of_water_by_the_bank_chest = new DetailedQuestStep(this, "Collect a Bucket of Water by the bank chest");
        deposit_all_in_the_bank_chest = new DetailedQuestStep(this, "Deposit all in the bank chest");
        enter_s_building_and_go_up_both_ladders = new DetailedQuestStep(this, "Enter 's building and go up both ladders");
        loot_28_s_hop_worlds = new DetailedQuestStep(this, "Loot 28 s (hop worlds)");
        deposit_all = new DetailedQuestStep(this, "Deposit all.");
        withdraw_coins = new DetailedQuestStep(this, "Withdraw: Coins.");
        collect_a_bucket_of_water_by_the_bank_chest = new DetailedQuestStep(this, "Collect a Bucket of Water by the bank chest");
        head_southwest_to_sunset_coast_be_careful_of_the = new DetailedQuestStep(this, "Head South-West to Sunset Coast. Be careful of the aggressive NPC's along the way as they can kill you if you do not pay attention.");
        loot_fly_fishing_rod_lobster_pot_3x_iron_bar_ho = new DetailedQuestStep(this, "Loot Fly Fishing Rod, Lobster Pot, 3x Iron Bar (hop worlds), Big Fishing Net & Feather");
        travel_with__to_aldarin = new DetailedQuestStep(this, "Travel with  to Aldarin");
        take_pot_of_flour = new DetailedQuestStep(this, "Take Pot of Flour");
        buy_6_onions = new DetailedQuestStep(this, "Buy 6 Onions");
        pick_a_cabbage = new DetailedQuestStep(this, "Pick a Cabbage");
        bank_south_and_deposit_all = new DetailedQuestStep(this, "Bank South and Deposit all");
        withdraw_28x_red_eclipse = new DetailedQuestStep(this, "Withdraw: 28x Red Eclipse");
        head_west_and_trade__and_sell_all_28_at_once = new DetailedQuestStep(this, "Head West and trade  and sell all 28 at once.");
        head_east_after_selling_eclipse_reds_and_buy_3_s_f = new DetailedQuestStep(this, "Head East after selling Eclipse reds and buy 3 s from the  in the pub. These give you a +1 agility boost to use the  shortcut later.");
        head_northeast_to_the_gem_store__buy_9x_uncut_sa = new DetailedQuestStep(this, "Head north-east to the Gem Store & buy 9x Uncut Sapphire, 10x Uncut Emerald, and as many Uncut Rubies as possible. (If the shop is out of stock, try to get a few or skip this step and mine a star after unlocking teleports to buy a  with stardust)");
        head_south_to___deposit_all_there = new DetailedQuestStep(this, "Head South to  & deposit all there");
        buy_steel_pickaxe_150_wines_20_mindbombs__20_st = new DetailedQuestStep(this, "Buy Steel Pickaxe, 150 Wines, 20 mindbombs & 20 Stews (They are infinite stock so super fast to collect here)");
        bank_at__and_deposit_all = new DetailedQuestStep(this, "Bank at  and deposit all.");
        withdraw_coins_research_notes_bronze_pickaxe = new DetailedQuestStep(this, "Withdraw: Coins, Research Notes, Bronze Pickaxe");
        home_teleport_to_lumbridge = new DetailedQuestStep(this, "Home Teleport to Lumbridge");
        head_to_the_wizards_tower = new DetailedQuestStep(this, "Head to the Wizards Tower");
        take_3x_logs = new DetailedQuestStep(this, "Take 3x Logs");
        search_the_altar_to_collect_the_ghosts_skull_run = new DetailedQuestStep(this, "Search the altar to collect the Ghost's skull. Run from the level 13 skeleton.");
        complete_rune_mysteries = new DetailedQuestStep(this, "Complete Rune Mysteries");
        teleport_to_rune_essence_mine = new DetailedQuestStep(this, "Teleport to Rune Essence Mine");
        take_3x_logs = new DetailedQuestStep(this, "Take 3x Logs");
        head_north_to_draynor_and_deposit_all = new DetailedQuestStep(this, "Head North to Draynor and Deposit all");
        withdraw_coins_mind_runes_small_fishing_net_on = new DetailedQuestStep(this, "Withdraw: Coins, Mind Runes, Small Fishing Net, Onion, Pickaxe, 454 Arrowshafts, 2x Wines");
        buy___10_teleport_cards_from = new DetailedQuestStep(this, "Buy  & 10 Teleport cards from");
        use_pages_on_chronicle_and_wield = new DetailedQuestStep(this, "Use Pages on Chronicle and wield");
        head_west_and_talk_to__to_start_pirates_treasure = new NpcStep(this, NpcID.REDBEARD_FRANK, new WorldPoint(3053, 3251, 0), "Head West and talk to  to start Pirate's Treasure");
        head_west_and_talk_to__to_start_pirates_treasure.addDialogSteps("1", "1");
        head_southwest_and_buy_a_harpoon_50_bait__10_fe = new DetailedQuestStep(this, "Head South-West and buy a Harpoon, 50 Bait & 10 Feather packs. Take Apron from the wall & wear.");
        make_454_headless_arrows = new DetailedQuestStep(this, "Make 454 Headless Arrows");
        take_ship_to_karamja_seamen_dressed_in_blue = new DetailedQuestStep(this, "Take Ship to Karamja (Seamen dressed in blue)");
        talk_to__and_ask_for_employment = new NpcStep(this, NpcID.LUTHAS, new WorldPoint(2938, 3154, 0), "Talk to  and ask for employment");
        talk_to__and_ask_for_employment.addDialogSteps("1");
        fish_raw_shrimps_karamja_easy_diary_drop_shrimps = new DetailedQuestStep(this, "Fish Raw Shrimps [Karamja Easy Diary] Drop Shrimps");
        pick_10_bananas = new DetailedQuestStep(this, "Pick 10 bananas");
        buy_karamja_rum = new DetailedQuestStep(this, "Buy Karamja Rum");
        fill_crate_with_bananas_and_use_karamja_rum_on_the = new ObjectStep(this, ObjectID.CRATE, new WorldPoint(2943, 3151, 0), "Fill Crate with bananas and use Karamja rum on the crate");
        take_boat_back_to_port_sarim = new DetailedQuestStep(this, "Take boat back to Port Sarim");
        trade_wydin_and_buy_raw_chicken_2x_raw_beef_3x_f = new DetailedQuestStep(this, "Trade Wydin and buy Raw Chicken, 2x Raw Beef, 3x Flour & 2x redberries");
        continue_pirates_treasure_by_talking_to_wydin_to_ = new DetailedQuestStep(this, "Continue Pirate's Treasure by talking to Wydin to get employed, and collect the rum from the crate.");
        buy_8x_raw_sardines = new DetailedQuestStep(this, "Buy 8x Raw Sardines");
        use_the_deposit_box_by_entrana_and_deposit_everyth = new DetailedQuestStep(this, "Use the Deposit box by Entrana and deposit everything except: Mind Runes, Coins, 1x Raw Beef, Karamja Rum, Onion, Pickaxe & 2x wines");
        return_to = new NpcStep(this, NpcID.REDBEARD_FRANK, new WorldPoint(3053, 3251, 0), "Return to");
        head_west_to_betty_and_buy_2x_eye_of_newt__200_mi = new DetailedQuestStep(this, "Head West to Betty and buy 2x Eye of Newt & 200 mind runes");
        head_southwest_and_complete_witches_potion_beef_ = new DetailedQuestStep(this, "Head South-West and complete Witches Potion (Beef twice on range to burn)");
        take_2x_logs_when_getting_the_rat_tail = new DetailedQuestStep(this, "Take 2x Logs when getting the rat tail");
        buy_moulds_ring_amulet_2x_necklace_bracelet_s = new DetailedQuestStep(this, "Buy moulds: Ring, Amulet, 2x Necklace, Bracelet, Sickle, Tiara, 3x Needle & 50 Thread (from  in Rimmington)");
        buy_3x_buckets__shears = new DetailedQuestStep(this, "Buy 3x Buckets & Shears");
        head_northwest_and_collect_a_snape_grass = new DetailedQuestStep(this, "Head North-West and collect a Snape Grass");
        milk_the_cow_3x_by_crafting_guild = new DetailedQuestStep(this, "Milk the cow 3x by Crafting guild");
        kill_a_cow__take_everything = new DetailedQuestStep(this, "Kill a cow & take everything");
        shear_a_sheep_by_the_makeover_mage = new DetailedQuestStep(this, "Shear a sheep by the Makeover Mage");
        take_falador_crumbling_wall_shortcut = new DetailedQuestStep(this, "Take Falador Crumbling wall Shortcut");
        bank_at_falador_west_bank_and_deposit_all = new DetailedQuestStep(this, "Bank at Falador West Bank and deposit all");
        withdraw_coins_mind_runes_raw_ratchickenbeef = new DetailedQuestStep(this, "Withdraw: Coins, Mind Runes, Raw Rat/Chicken/Beef, 10x Wines, Empty Bucket, Chest Key, Cheese");
        get_a_haircut_north = new DetailedQuestStep(this, "Get a haircut North");
        fill_bucket_on_pump = new DetailedQuestStep(this, "Fill Bucket on Pump");
        head_south_and_talk_to_the__and_start_knights_swo = new NpcStep(this, NpcID.SQUIRE, new WorldPoint(2750, 3507, 2), "Head South and talk to the  and start Knight's Sword");
        head_south_and_talk_to_the__and_start_knights_swo.addDialogSteps("1", "2", "1", "1");
        get_a_mahogany_home_beginner_contract_from__try_a = new DetailedQuestStep(this, "Get a Mahogany Home Beginner Contract from  (try and do these whenever passing if viable (aka if Hosidius and you're nearby, detour and complete it. If not they're done later but may be inefficient) - Mahogany homes plugin or notepad to remember your tasks.");
        kill_a_duck_in_falador_park = new DetailedQuestStep(this, "Kill a duck in Falador Park");
        buy_6x_woad_leaves_from = new DetailedQuestStep(this, "Buy 6x Woad Leaves from");
        head_north_of_falador_and_kill_a_black_bear_safes = new DetailedQuestStep(this, "Head North of Falador and kill a Black Bear (safespot on trees as it is a 2x2). Collect the Raw Bear Meat, Bones & fur.");
        head_to_taverly_and_talk_to_the__to_start_witches_ = new DetailedQuestStep(this, "Head to Taverly and talk to the  to start Witches House");
        head_north_and_talk_to__to_start_druidic_ritual = new NpcStep(this, NpcID.KAQEMEEX, new WorldPoint(2925, 3486, 0), "Head North and talk to  to start Druidic Ritual");
        head_north_and_talk_to__to_start_druidic_ritual.addDialogSteps("2", "1");
    }

    @Override
    public List<PanelDetails> getPanels()
    {
        List<PanelDetails> panels = new ArrayList<>();

        PanelDetails startingoutPanel = new PanelDetails("Starting out", Arrays.asList(all_settings__disable_levelup, head_northwest_to___drop_air__mind_runes_and_cl, sell_bronze_dagger_sword_wooden_shield__shortbo, head_east__start_x_marks_the_spot_on_veos___comp, bank_at_lumbridge_castle_top_floor_and_deposit_all, move_coins_into_first_bank_slot__runes_to_the_top));
        panels.add(startingoutPanel);
        PanelDetails restlessghostPanel = new PanelDetails("Restless Ghost", Arrays.asList(talk_to));
        panels.add(restlessghostPanel);
        PanelDetails lumbridgeeasydiaryPanel = new PanelDetails("Lumbridge Easy Diary", Arrays.asList(pickpocket_a_manwoman, check_playtime_on, train_draynor_agility_to_5_agility, teleport_to_rune_essence_mine));
        panels.add(lumbridgeeasydiaryPanel);
        PanelDetails runemysteriesPanel = new PanelDetails("Rune Mysteries", Arrays.asList(go_upstairs_and_talk_to));
        panels.add(runemysteriesPanel);
        PanelDetails treegnomevillagePanel = new PanelDetails("Tree Gnome Village", Arrays.asList(go_upstairs_again_and_collect_4x_logs_on_the_top_f, collect_3x_logs_next_to_the_stairs, collect_3x_logs));
        panels.add(treegnomevillagePanel);
        PanelDetails familycrestquestPanel = new PanelDetails("Family Crest Quest", Arrays.asList(keep_the_shrimps_in_your_bank_for_later));
        panels.add(familycrestquestPanel);
        PanelDetails bank1Panel = new PanelDetails("Bank 1", Arrays.asList(withdraw_coins_air_runes_mind_runes_bread_spa, go_down_south_staircase_twice, collect_the_empty_jug_bowl__knife_in_lumbridge_k, complete_2nd_step_of_x_marks_the_spot, head_west_towards_draynor_hugging_the_fence_to_avo, talk_to__in_the_lumbridge_swamp_for_ghost_speak_am, take_leather_gloves_on_the_table_inside_his_house_, head_to_the_wizards_tower, take_leather_boots_off_the_table__wield, head_to_the_basement__talk_to__to_continue_rune_m, return_to_draynor__talk_to__and_obtain_forestry_k, bank_at_draynor_and_deposit_all));
        panels.add(bank1Panel);
        PanelDetails monksfriendPanel = new PanelDetails("Monk's Friend", Arrays.asList(fill_the_jug__bowl_on_the_sink_in_the_kitchen));
        panels.add(monksfriendPanel);
        PanelDetails druidicritualPanel = new PanelDetails("Druidic Ritual", Arrays.asList(kill_a_giant_rat_with_wind_strike_and_collect_the_));
        panels.add(druidicritualPanel);
        PanelDetails clientofkourenddruidicritualPanel = new PanelDetails("Client of Kourend + Druidic Ritual", Arrays.asList(kill_a_chicken_take_everything_make_sure_you_get));
        panels.add(clientofkourenddruidicritualPanel);
        PanelDetails bank2Panel = new PanelDetails("Bank 2", Arrays.asList(withdraw_coins_spade_feather__mysterious_orb, complete_3rd_step_of_x_marks_the_spot, talk_to__and_start_vampyre_slayer, go_up_the_stairs_and_collect_4x_garlic_from_the_cu, bank_at_draynor_and_deposit_the_garlic__cheese, talk_to___buy_5_wines_hop_worlds_and_buy_10_in_t, start, complete_4th_step_of_x_marks_the_spot, head_west_to_port_sarim_and_talk_to__to_complete_x, destroy_the_lamp_you_can_collect_this_later_as_yo, travel_to_port_piscarilius, take_minecart_to_shayzien_east, open_minimap__follow_the_path_southwest_to_shayz, take_the_beer, use_your_feather_on_the_enchanted_scroll_in_your_i, talk_to__for_client_of_kourend, take_tinderbox, home_teleport_to_lumbridge, talk_to__and_buy_a_steel_axe, talk_to, talk_to__and_be_teleported_to_stronghold_of_securi, complete_3_floors_of_stronghold_of_security, on_floor_3_spider_max_is_7_so_if_you_take_3_or_mo, max_is_9_so_drink_on_any_damage, once_you_have_10000gp_from_floor_3_leave_via_the, collect_3x_beer_inside_the_longhall, collect_a_doogle_leaf_south_of_gertrude, bank_at_varrock_west_bank_and_deposit_all));
        panels.add(bank2Panel);
        PanelDetails witchshousePanel = new PanelDetails("Witch's House", Arrays.asList(collect_cheese_from));
        panels.add(witchshousePanel);
        PanelDetails fishingcontestPanel = new PanelDetails("Fishing Contest", Arrays.asList(you_can_get_multiple_garlic_by_spamclicking_the_cu));
        panels.add(fishingcontestPanel);
        PanelDetails clientofkourendPanel = new PanelDetails("Client of Kourend", Arrays.asList(talk_to));
        panels.add(clientofkourendPanel);
        PanelDetails shadowofthestormgoblindiplomacyPanel = new PanelDetails("Shadow of the Storm, Goblin Diplomacy", Arrays.asList(take_wizard_hat__orange_dye));
        panels.add(shadowofthestormgoblindiplomacyPanel);
        PanelDetails cookingguildPanel = new PanelDetails("Cooking Guild", Arrays.asList(buy_chefs_hat));
        panels.add(cookingguildPanel);
        PanelDetails mourningsendpt2Panel = new PanelDetails("Mournings End Pt 2", Arrays.asList(collect_a_cooked_meat));
        panels.add(mourningsendpt2Panel);
        PanelDetails gertrudescatPanel = new PanelDetails("Gertrudes Cat", Arrays.asList(head_east_and_talk_to));
        panels.add(gertrudescatPanel);
        PanelDetails bank3Panel = new PanelDetails("Bank 3", Arrays.asList(withdraw_coins_bones_beer, use_the_bones_on_the__whenever_you_find_him, head_east_and_buy_an_air_staff_from__equip_it, head_south__talk_to__and_start_demon_slayer_, buy_pink_skirt_brown_apron__silk_wear_brown_apr, head_south_to_the_sword_shop_and_go_up_the_ladder, head_north, buy_a_newspaper_from, talk_to__to_continue_gertrudes_cat, complete_children_of_the_sun, return_down_the_stairs_and_talk_to__and_start_shie, search_for_book_and_talk_to__again, head_east_and_up_the_stairs_in_the_kitchen, collect_both_buckets_and_fill_one_up_downstairs_u, head_to__and_start_priest_in_peril, talk_to__and_start_daddys_home_in_a_house_the_ea, pick_up_the_saw, enter_varrock_sewer_and_take_the_northwest_path_t, enter_varrock_museum_and_head_downstairs_and_talk_, bank_at_varrock_east_bank_and_deposit_all));
        panels.add(bank3Panel);
        PanelDetails varrockeasydiaryPanel = new PanelDetails("Varrock Easy Diary", Arrays.asList(head_south__trade, cut_the_dying_tree));
        panels.add(varrockeasydiaryPanel);
        PanelDetails vampyreslayerPanel = new PanelDetails("Vampyre Slayer", Arrays.asList(head_east_and_talk_to));
        panels.add(vampyreslayerPanel);
        PanelDetails romeojulietPanel = new PanelDetails("Romeo & Juliet", Arrays.asList(talk_to));
        panels.add(romeojulietPanel);
        PanelDetails childrenofthesunPanel = new PanelDetails("Children of the Sun", Arrays.asList(talk_to));
        panels.add(childrenofthesunPanel);
        PanelDetails demonslayerPanel = new PanelDetails("Demon Slayer", Arrays.asList(talk_to, head_north_and_go_up_2x_stairs_and_talk_to));
        panels.add(demonslayerPanel);
        PanelDetails knightsswordPanel = new PanelDetails("Knight's Sword", Arrays.asList(take_the_pie_dish));
        panels.add(knightsswordPanel);
        PanelDetails bank4Panel = new PanelDetails("Bank 4", Arrays.asList(withdraw_coins_saw_hammer_knife_bronze_axe_r, talk_to__to_continue_rune_mysteries, light_both_logs_in_the_house_right_next_to_the_run, destroy_all_the_furniture_in_the_house, talk_to__to_continue_daddys_home, take_2x_logs__2x_ashes_after_cutscene, search_crates_for_3x_waxwood_log, bank_the_ashes, head_northeast_to_the_lumberyard, collect_the_logs__fletch_2100_arrowshafts_hop_b, collect_11_logs__make_10_into_planks_make_the_3_, buy_5x_bolts_of_cloth__100_steel_nails, return_to___continue_daddys_home, light_1_log__take_the_1x_log, collect_ashes, trade__and_buy_1x_fireairearth_pack_2x_water_pa, complete_daddys_home_at_marlo, open_the_crate, bank_at_varrock_east_bank));
        panels.add(bank4Panel);
        PanelDetails bank5Panel = new PanelDetails("Bank 5", Arrays.asList(withdraw_leather_gloves_to_pick_nettles, travel_east_to___travel_to_varlamore, open_the_minimap_and_head_south_out_of_the_city, take_the_3x_logs_rope_pestle__mortar__vial_of_, head_west_to_the_hunters_guild, collect_the_needle, collect_a_bucket_of_water_by_the_bank_chest, deposit_all_in_the_bank_chest, enter_s_building_and_go_up_both_ladders, loot_28_s_hop_worlds, deposit_all));
        panels.add(bank5Panel);
        PanelDetails skippythemogresPanel = new PanelDetails("Skippy & The Mogres", Arrays.asList(pick_2_nettles));
        panels.add(skippythemogresPanel);
        PanelDetails recipefordisasterPanel = new PanelDetails("Recipe for Disaster", Arrays.asList(collect_1_sweetcorn));
        panels.add(recipefordisasterPanel);
        PanelDetails bank6Panel = new PanelDetails("Bank 6", Arrays.asList(withdraw_coins, collect_a_bucket_of_water_by_the_bank_chest, head_southwest_to_sunset_coast_be_careful_of_the, loot_fly_fishing_rod_lobster_pot_3x_iron_bar_ho, travel_with__to_aldarin, take_pot_of_flour, bank_south_and_deposit_all));
        panels.add(bank6Panel);
        PanelDetails yellowdyesPanel = new PanelDetails("Yellow Dyes", Arrays.asList(buy_6_onions));
        panels.add(yellowdyesPanel);
        PanelDetails blackknightsfortressPanel = new PanelDetails("Black Knight's Fortress", Arrays.asList(pick_a_cabbage));
        panels.add(blackknightsfortressPanel);
        PanelDetails bank7Panel = new PanelDetails("Bank 7", Arrays.asList(withdraw_28x_red_eclipse, head_west_and_trade__and_sell_all_28_at_once, head_east_after_selling_eclipse_reds_and_buy_3_s_f, head_northeast_to_the_gem_store__buy_9x_uncut_sa, head_south_to___deposit_all_there, buy_steel_pickaxe_150_wines_20_mindbombs__20_st, bank_at__and_deposit_all));
        panels.add(bank7Panel);
        PanelDetails bank8Panel = new PanelDetails("Bank 8", Arrays.asList(withdraw_coins_research_notes_bronze_pickaxe, home_teleport_to_lumbridge, head_to_the_wizards_tower, take_3x_logs, search_the_altar_to_collect_the_ghosts_skull_run, complete_rune_mysteries, take_3x_logs, head_north_to_draynor_and_deposit_all));
        panels.add(bank8Panel);
        PanelDetails bank9Panel = new PanelDetails("Bank 9", Arrays.asList(withdraw_coins_mind_runes_small_fishing_net_on, buy___10_teleport_cards_from, use_pages_on_chronicle_and_wield, head_west_and_talk_to__to_start_pirates_treasure, head_southwest_and_buy_a_harpoon_50_bait__10_fe, make_454_headless_arrows, take_ship_to_karamja_seamen_dressed_in_blue, talk_to__and_ask_for_employment, fish_raw_shrimps_karamja_easy_diary_drop_shrimps, pick_10_bananas, buy_karamja_rum, fill_crate_with_bananas_and_use_karamja_rum_on_the, trade_wydin_and_buy_raw_chicken_2x_raw_beef_3x_f, continue_pirates_treasure_by_talking_to_wydin_to_, buy_8x_raw_sardines, use_the_deposit_box_by_entrana_and_deposit_everyth, return_to, head_west_to_betty_and_buy_2x_eye_of_newt__200_mi, head_southwest_and_complete_witches_potion_beef_, take_2x_logs_when_getting_the_rat_tail, buy_moulds_ring_amulet_2x_necklace_bracelet_s, buy_3x_buckets__shears, head_northwest_and_collect_a_snape_grass, milk_the_cow_3x_by_crafting_guild, kill_a_cow__take_everything, shear_a_sheep_by_the_makeover_mage, bank_at_falador_west_bank_and_deposit_all));
        panels.add(bank9Panel);
        PanelDetails karamjaeasydiaryPanel = new PanelDetails("Karamja Easy Diary", Arrays.asList(take_boat_back_to_port_sarim));
        panels.add(karamjaeasydiaryPanel);
        PanelDetails faladoreasydiaryPanel = new PanelDetails("Falador Easy Diary", Arrays.asList(take_falador_crumbling_wall_shortcut, get_a_haircut_north, fill_bucket_on_pump, kill_a_duck_in_falador_park));
        panels.add(faladoreasydiaryPanel);
        PanelDetails bank10Panel = new PanelDetails("Bank 10", Arrays.asList(withdraw_coins_mind_runes_raw_ratchickenbeef, head_south_and_talk_to_the__and_start_knights_swo, get_a_mahogany_home_beginner_contract_from__try_a, buy_6x_woad_leaves_from, head_north_of_falador_and_kill_a_black_bear_safes, head_to_taverly_and_talk_to_the__to_start_witches_, head_north_and_talk_to__to_start_druidic_ritual));
        panels.add(bank10Panel);
        return panels;
    }

}
